first import necessary modules

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [4]:
df = pd.read_csv("spec_RBCL_16s.csv")
df.head()

C:\Users\rah10\miniconda3\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (29,34,36) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,UniqueID,TempID,EventID,Collector,Apidae,AspergillusSpp,AscosphaeraSpp,ApicystisSpp,CrithidiaExpoeki,CrithidiaBombi,...,RBCL:Scrophulariaceae_Verbascum_thapsus,RBCL:Fabaceae_Dalea_polygonoides,RBCL:Brassicaceae_Capsella__bursa-pastoris,RBCL:Fabaceae_Trifolium_sp._A,RBCL:Scrophulariaceae_Scrophularia_sp._A,RBCL:Rosaceae_Sanguisorba_sp._A,RBCL:Brassicaceae_Sisymbrium_sp._A,RBCL:Rosaceae_Rubus__sp._A,RBCL:Geraniaceae_Geranium__sp._A,RBCL:Apiaceae_Unknown_sp._M
0,17648,17648,NaN,PM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17649,17649,NaN,PM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17650,17650,NaN,PM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,17653,17653,NaN,PM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,17654,17654,NaN,PM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

drop columns with na

In [43]:
rbcl = df[['Order', 'Family', 'Genus', 'Species']]

#for i in df.columns:
#    if i.startswith('RBCL'):
    
rbcl_df = [rbcl.append() for i in df.columns if df.columns == df.str.startswith('RBCL')]

AttributeError: 'DataFrame' object has no attribute 'str'

In [33]:
rbcl.head()

         Order      Family         Genus     Species
0  Hymenoptera      Apidae   Heterosarus      bakeri
1  Hymenoptera  Halictidae  Lasioglossum  ruidosense
2  Hymenoptera      Apidae       Andrena  apacheorum
3  Hymenoptera  Halictidae  Lasioglossum  ruidosense
4  Hymenoptera      Apidae   Heterosarus      bakeri